/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    tenants: Tenant;
    subscriptions: Subscription;
    'im-bindings': ImBinding;
    'routing-rules': RoutingRule;
    'usage-records': UsageRecord;
    'audit-log': AuditLog;
    'tenant-role-kb': TenantRoleKb;
    employees: Employee;
    'product-modules': ProductModule;
    projects: Project;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    'im-bindings': ImBindingsSelect<false> | ImBindingsSelect<true>;
    'routing-rules': RoutingRulesSelect<false> | RoutingRulesSelect<true>;
    'usage-records': UsageRecordsSelect<false> | UsageRecordsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'tenant-role-kb': TenantRoleKbSelect<false> | TenantRoleKbSelect<true>;
    employees: EmployeesSelect<false> | EmployeesSelect<true>;
    'product-modules': ProductModulesSelect<false> | ProductModulesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * admin 看全量；customer 仅看自己 tenant
   */
  role: 'admin' | 'customer';
  /**
   * 仅当 role=customer 时必填；admin 留空
   */
  tenant?: (number | null) | Tenant;
  /**
   * 可选。客户面问候语用
   */
  display_name?: string | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * 运营录入的客户主体，所有订阅/路由/IM 凭证都挂在 tenant 下
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * 小写英数+下划线，3-32 位，如 acme_corp。一旦创建不可改
   */
  tenant_id: string;
  /**
   * 营业执照上的全称
   */
  company_name: string;
  industry?: ('tech' | 'finance' | 'manufacturing' | 'retail' | 'education' | 'general') | null;
  plan?: ('trial' | 'standard' | 'pro') | null;
  status?: ('active' | 'suspended') | null;
  /**
   * 用于报表抬头与权限识别。多个 ID 用英文逗号隔开
   */
  boss_user_ids?: string | null;
  /**
   * 每个自然月可调用 LLM 的总次数上限（兜底，模块级配额由订阅控制）
   */
  monthly_quota?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * 客户开通的模块（数据安全 / 智能报表）+ 套餐与配额
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  /**
   * 关联的客户
   */
  tenant: number | Tenant;
  module_id: 'yguard' | 'reports';
  plan: 'trial' | 'standard' | 'pro';
  status: 'active' | 'suspended' | 'expired';
  started_at: string;
  /**
   * 留空 = 永久
   */
  expires_at?: string | null;
  quota_monthly: number;
  /**
   * 本月已消耗，由系统自动更新；运营手动改通常表示重置
   */
  quota_used: number;
  /**
   * 模块特定参数（JSON）。比如 reports 的报表模板 ID
   */
  config?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 客户 IM 渠道凭据。1 个 tenant × 1 个 channel 唯一
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "im-bindings".
 */
export interface ImBinding {
  id: number;
  tenant: number | Tenant;
  channel: 'dingtalk' | 'wecom' | 'feishu';
  /**
   * 钉钉 AppKey / 企微 CorpId / 飞书 App ID
   */
  app_key?: string | null;
  /**
   * 只在创建/更新时填写。保存后即清空，密文存到下方 app_secret_enc
   */
  app_secret_plain?: string | null;
  /**
   * Fernet 加密结果（不可读）。要更新请填上方明文字段
   */
  app_secret_enc?: string | null;
  /**
   * 密钥是否已配置（不展示密文）
   */
  has_app_secret?: boolean | null;
  corp_id?: string | null;
  agent_id?: string | null;
  callback_token?: string | null;
  aes_key_plain?: string | null;
  aes_key_enc?: string | null;
  has_aes_key?: boolean | null;
  status: 'active' | 'suspended';
  updatedAt: string;
  createdAt: string;
}
/**
 * 消息分发规则。priority 数字小先匹配，default 兜底放最后
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routing-rules".
 */
export interface RoutingRule {
  id: number;
  tenant: number | Tenant;
  channel: 'dingtalk' | 'wecom' | 'feishu' | '*';
  match_type: 'prefix' | 'mention' | 'llm' | 'default';
  /**
   * 前缀类型填「/report」；@提及类型填「@报表」；兜底类型留空
   */
  pattern?: string | null;
  target_module_id: 'ipguard' | 'reports';
  /**
   * 数字越小越先匹配。建议：前缀 10、@提及 20、兜底 999
   */
  priority: number;
  enabled: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * 只读。由后端业务自动追加，admin 仅查看与导出
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-records".
 */
export interface UsageRecord {
  id: number;
  tenant: number | Tenant;
  module_id: 'ipguard' | 'reports';
  channel?: ('dingtalk' | 'wecom' | 'feishu') | null;
  occurred_at: string;
  tokens_in: number;
  tokens_out: number;
  cost_cents: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * 只读。所有写操作的痕迹都在这里
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: number;
  /**
   * 事件归属客户。系统级事件可留空
   */
  tenant?: (number | null) | Tenant;
  /**
   * user.email 或系统标识，如 system / mcp:agent-name
   */
  actor: string;
  /**
   * 如 tenants.create / subscriptions.update / im-bindings.delete
   */
  action: string;
  /**
   * collection slug 加 ID，如 tenants/abc123
   */
  target?: string | null;
  /**
   * 一句话描述（客户面展示用）
   */
  summary?: string | null;
  /**
   * 改动内容 / 调用参数
   */
  payload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 每租户每角色的 SOUL 模板、可见字段、红线规则。control-plane provision worker 拉这些数据渲染 hermes profile 的 SOUL.md（tenant 级合成，不再 per-module）
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-role-kb".
 */
export interface TenantRoleKb {
  id: number;
  /**
   * 关联到 Tenants collection；通过 tenant.tenant_id 查询
   */
  tenant: number | Tenant;
  /**
   * 业务角色，决定 SOUL.md 的 ## 当面对 X 段渲染。default 段是总则（不限角色）
   */
  role: 'boss' | 'dept_head' | 'boss_assistant' | 'hr_manager' | 'it_admin' | 'employee' | 'default';
  /**
   * 渲染到 hermes profile SOUL.md 的对应角色段。可用占位符 {{peer_role}} / {{tenant_id}} / {{module}}（control-plane provision worker 渲染时替换）
   */
  soul_template: string;
  /**
   * 本角色可见的业务字段列表；未列出的字段在响应中脱敏（控制由 hermes skill handler 实施，本 collection 仅声明）
   */
  visible_fields?:
    | {
        /**
         * 业务字段名，如 employee_name / device_serial / file_name
         */
        field: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 注入到 SOUL.md 总则段；hermes prompt 显式提醒 LLM 遵守
   */
  red_lines?:
    | {
        /**
         * 规则文本，如 "不显示真实姓名" / "不显示原始 SQL"
         */
        rule: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 仅启用的 KB 被 provision worker 拉取并渲染
   */
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 员工身份主表（钉钉同步 + role 业务字段）。同步字段 readOnly；仅 role 可改。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees".
 */
export interface Employee {
  id: number;
  /**
   * 关联到 Tenants collection
   */
  tenant: number | Tenant;
  /**
   * 钉钉 userid（来自 dingtalk）。一个 tenant 内 unique；同步 worker 写，禁手改
   */
  staff_id: string;
  /**
   * 同步自钉钉
   */
  name: string;
  email?: string | null;
  /**
   * 同步自钉钉，跨 tenant 不强约束（自由文本）
   */
  department: string;
  /**
   * 钉钉 dept_id（用于 ACL 跨部门判定，dept_head 仅本部门）
   */
  department_id?: string | null;
  /**
   * 同步自钉钉 manager_userid；可空（boss 无上级）
   */
  manager_staff_id?: string | null;
  /**
   * 钉钉 free text 职位描述
   */
  position?: string | null;
  /**
   * 同步自钉钉 user_leave_org 事件触发 false。禁用员工的 ACL 调用一律拒绝
   */
  is_active?: boolean | null;
  /**
   * 最后一次从钉钉同步该员工的时间戳
   */
  dingtalk_synced_at?: string | null;
  /**
   * 决定 ACL 行为。钉钉同步进来默认 employee，客户管理员升级时改。
   */
  role: 'boss' | 'dept_head' | 'boss_assistant' | 'hr_manager' | 'it_admin' | 'project_admin' | 'employee';
  updatedAt: string;
  createdAt: string;
}
/**
 * 集团子模块产品元信息（卖点 + 引导话术），供 SOUL.md 渲染使用
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-modules".
 */
export interface ProductModule {
  id: number;
  /**
   * 与 Subscriptions.module_id 严格对齐：yguard / reports（未来扩展时新增行）
   */
  module_id: string;
  /**
   * 如"数据安全"、"智能报表"
   */
  label_zh: string;
  /**
   * ≤80 字符，用于 SOUL.md 摘要段和 handler 拒绝文案
   */
  tagline: string;
  /**
   * 3-5 条，每条 ≤50 字符
   */
  key_features: {
    value: string;
    id?: string | null;
  }[];
  /**
   * 面向哪类客户、适合什么场景
   */
  target_audience?: string | null;
  /**
   * 3-6 条，让 LLM 学会识别"这是 X 模块的需求"
   */
  trigger_examples: {
    value: string;
    id?: string | null;
  }[];
  /**
   * 如"请联系贵司客户经理或运营开通"；LLM 引用此字段生成回复
   */
  upsell_cta: string;
  /**
   * 数字越小越靠前；默认 100
   */
  order?: number | null;
  /**
   * 停售产品设 false，不进入 SOUL.md 产品矩阵段
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 项目主数据 SoT（ADR-0013）。销售部单向立项；reports.projects 是只读 mirror。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * 关联到 Tenants collection
   */
  tenant: number | Tenant;
  /**
   * 全流程流转锚，tenant 内唯一。销售立项时写入，其他部门对齐到此名
   */
  canonical_name: string;
  /**
   * 5 值生命周期。mirror 时映射到 reports.projects.stage（ADR-0013 D4）
   */
  status: 'prospecting' | 'contracted' | 'active' | 'accepted' | 'closed';
  /**
   * 发起立项的销售员 staff_id（钉钉 userid 明文）
   */
  owner_staff_id?: string | null;
  /**
   * 跨部门参与的部门名列表。本轮只建字段，聚合消费逻辑后续阶段
   */
  participating_departments?: string[] | null;
  created_via: 'sales_excel' | 'admin_ui' | 'llm_aligned' | 'migration';
  /**
   * 员工写过的别名变体，用于 LLM 归一化对齐命中
   */
  aliases?: string[] | null;
  /**
   * 项目对应的客户单位或学校名（可空）
   */
  client_school?: string | null;
  started_at?: string | null;
  expected_done_at?: string | null;
  /**
   * 0-100，cron 跨部门聚合回填。本轮只建字段
   */
  progress_summary?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  tenants?: {
    /**
     * Allow clients to find tenants.
     */
    find?: boolean | null;
    /**
     * Allow clients to create tenants.
     */
    create?: boolean | null;
    /**
     * Allow clients to update tenants.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete tenants.
     */
    delete?: boolean | null;
  };
  subscriptions?: {
    /**
     * Allow clients to find subscriptions.
     */
    find?: boolean | null;
    /**
     * Allow clients to create subscriptions.
     */
    create?: boolean | null;
    /**
     * Allow clients to update subscriptions.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete subscriptions.
     */
    delete?: boolean | null;
  };
  imBindings?: {
    /**
     * Allow clients to find im-bindings.
     */
    find?: boolean | null;
    /**
     * Allow clients to create im-bindings.
     */
    create?: boolean | null;
    /**
     * Allow clients to update im-bindings.
     */
    update?: boolean | null;
  };
  routingRules?: {
    /**
     * Allow clients to find routing-rules.
     */
    find?: boolean | null;
    /**
     * Allow clients to create routing-rules.
     */
    create?: boolean | null;
    /**
     * Allow clients to update routing-rules.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete routing-rules.
     */
    delete?: boolean | null;
  };
  usageRecords?: {
    /**
     * Allow clients to find usage-records.
     */
    find?: boolean | null;
  };
  auditLog?: {
    /**
     * Allow clients to find audit-log.
     */
    find?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'im-bindings';
        value: number | ImBinding;
      } | null)
    | ({
        relationTo: 'routing-rules';
        value: number | RoutingRule;
      } | null)
    | ({
        relationTo: 'usage-records';
        value: number | UsageRecord;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'tenant-role-kb';
        value: number | TenantRoleKb;
      } | null)
    | ({
        relationTo: 'employees';
        value: number | Employee;
      } | null)
    | ({
        relationTo: 'product-modules';
        value: number | ProductModule;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  tenant?: T;
  display_name?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  tenant_id?: T;
  company_name?: T;
  industry?: T;
  plan?: T;
  status?: T;
  boss_user_ids?: T;
  monthly_quota?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  tenant?: T;
  module_id?: T;
  plan?: T;
  status?: T;
  started_at?: T;
  expires_at?: T;
  quota_monthly?: T;
  quota_used?: T;
  config?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "im-bindings_select".
 */
export interface ImBindingsSelect<T extends boolean = true> {
  tenant?: T;
  channel?: T;
  app_key?: T;
  app_secret_plain?: T;
  app_secret_enc?: T;
  has_app_secret?: T;
  corp_id?: T;
  agent_id?: T;
  callback_token?: T;
  aes_key_plain?: T;
  aes_key_enc?: T;
  has_aes_key?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "routing-rules_select".
 */
export interface RoutingRulesSelect<T extends boolean = true> {
  tenant?: T;
  channel?: T;
  match_type?: T;
  pattern?: T;
  target_module_id?: T;
  priority?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usage-records_select".
 */
export interface UsageRecordsSelect<T extends boolean = true> {
  tenant?: T;
  module_id?: T;
  channel?: T;
  occurred_at?: T;
  tokens_in?: T;
  tokens_out?: T;
  cost_cents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  tenant?: T;
  actor?: T;
  action?: T;
  target?: T;
  summary?: T;
  payload?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenant-role-kb_select".
 */
export interface TenantRoleKbSelect<T extends boolean = true> {
  tenant?: T;
  role?: T;
  soul_template?: T;
  visible_fields?:
    | T
    | {
        field?: T;
        id?: T;
      };
  red_lines?:
    | T
    | {
        rule?: T;
        id?: T;
      };
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees_select".
 */
export interface EmployeesSelect<T extends boolean = true> {
  tenant?: T;
  staff_id?: T;
  name?: T;
  email?: T;
  department?: T;
  department_id?: T;
  manager_staff_id?: T;
  position?: T;
  is_active?: T;
  dingtalk_synced_at?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-modules_select".
 */
export interface ProductModulesSelect<T extends boolean = true> {
  module_id?: T;
  label_zh?: T;
  tagline?: T;
  key_features?:
    | T
    | {
        value?: T;
        id?: T;
      };
  target_audience?: T;
  trigger_examples?:
    | T
    | {
        value?: T;
        id?: T;
      };
  upsell_cta?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  tenant?: T;
  canonical_name?: T;
  status?: T;
  owner_staff_id?: T;
  participating_departments?: T;
  created_via?: T;
  aliases?: T;
  client_school?: T;
  started_at?: T;
  expected_done_at?: T;
  progress_summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  tenants?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  subscriptions?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  imBindings?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  routingRules?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  usageRecords?:
    | T
    | {
        find?: T;
      };
  auditLog?:
    | T
    | {
        find?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}